name: "baldurs-bank-dev"
services:
  asp:
    build:
      context: ./user
      dockerfile: Dockerfile.dev
      args:
        HOST: "${HOST}"
        SECRET_KEY: "${SECRET_KEY}"
        MSSQL_URL: "${MSSQL_URL}"
        GEO_IP_PATH: "/geoip/database/GeoLite2-City.mmdb"
        GEO_IP_ACCOUNT_ID: "${GEO_IP_ACCOUNT_ID}"
        GEO_IP_LICENSE_KEY: "${GEO_IP_LICENSE_KEY}"
    image: asp
    environment:
      HOST: "${HOST}"
      SECRET_KEY: "${SECRET_KEY}"
      MSSQL_URL: "${MSSQL_URL}"
      GEO_IP_PATH: "/geoip/database/GeoLite2-City.mmdb"
      GEO_IP_ACCOUNT_ID: "${GEO_IP_ACCOUNT_ID}"
      GEO_IP_LICENSE_KEY: "${GEO_IP_LICENSE_KEY}"
    volumes:
      - ./asp/src:/app/src
    networks:
      - net
    depends_on:
      - mssql
networks:
  net:
    driver: bridge
volumes:
  storage-mssql:
    driver: local